project 'JGTool.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

inhibit_all_warnings!

target 'JGTool' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JGTool

   pod 'FDFullscreenPopGesture', '1.1'
   pod 'AFNetworking', '~> 3.1.0'
   pod 'MJExtension', '~> 3.0.13'
   pod 'MBProgressHUD', '~> 1.1.0'
   pod 'SDWebImage', '~> 4.2.0'
   pod 'MJRefresh', '~> 3.1.15'
   pod 'IQKeyboardManager', '~> 6.2.0' #键盘遮盖
   pod 'SDAutoLayout'
  
   pod 'SocketRocket', '~> 0.5.1' #webscoket
   pod 'AWSS3', '~> 2.6.35'  #亚马逊S3云存储


  target 'JGToolTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JGToolUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
